#/home/lim/pinky/src/move_to_target/my_map_waypoints.yaml
# 2025.11.20 충전소를 원점으로 한 좌표따기 끝

waypoints:
  - name: "Origin"
    pose:
      position: {x: 0.0, y: 0.0}
      yaw: 0
    neighbors: ["1번", "2번"]


  - name: "1번"
    pose:
      position: {x: 1.566143915827006, y: -0.7624471393671794}
      yaw: 270
    neighbors: ["Origin", "2번", "8번"]


  - name: "2번"
    pose:
      position: {x: 1.6387578681704877, y: -0.23332368745191576}
      yaw: 180
    neighbors: ["1번", "3번"]


  - name: "3번"
    pose:
      position: {x: 1.6387578681704877, y: 0.03691246629888334}
      yaw: 90
    neighbors: ["1번", "Origin"]


  - name: "4번"
    pose:
      position: {x: 1.6387578681704877, y: 0.5627939596243186}
      yaw: 270
    neighbors: ["3번", "5번"]


  - name: "5번"
    pose:
      position: {x: 1.6387578681704877, y: 1.040160507214238}
      yaw: 0
    neighbors: ["4번", "6번", "12번"]


  - name: "6번"
    pose:
      position: {x: 1.6387578681704877, y: 1.3706947569793049}
      yaw: 270
    neighbors: ["5번", "7번"]


  - name: "7번"
    pose:
      position: {x: 1.6387578681704877, y: 1.8305054158827394}
      yaw: 180
    neighbors: ["6번", "14번"]


  - name: "8번"
    pose:
      position: {x: 1.0361602096904161, y: -0.5853056969858791}
      yaw: 90
    neighbors: ["10번", "9번", "1번"]


  - name: "9번"
    pose:
      position: {x: 1.1562263970596303, y: 0.08201862789207194}
      yaw: 270
    neighbors: ["8번", "11번", "3번"]


  - name: "10번"
    pose:
      position: {x: 0.877987127700968, y: -0.5853056969858791}
      yaw: 0
    neighbors: ["8번", "11번"]


    - name: "11번"
    pose:
      position: {x: 0.8559493965290068, y: 0.08201862789207194}
      yaw: 270
    neighbors: [10번", "9번", "16번"]


  - name: "12번"
    pose:
      position: {x: 1.120242447529739, y: 1.040160507214238}
      yaw: 180
    neighbors: ["5번", "13번"]


  - name: "13번"
    pose:
      position: {x: 0.7606641931030175, y: 1.040160507214238}
      yaw: 90
    neighbors: ["12번", "20번"]


  - name: "14번"
    pose:
      position: {x: 1.1614882687795596, y: 1.8305054158827394}
      yaw: 270
    neighbors: ["7번", "15번"]


  - name: "15번"
    pose:
      position: {x: 0.6953613809685402, y: 1.8305054158827394}
      yaw: 0
    neighbors: ["14번", "22번"]


  - name: "16번"
    pose:
      position: {x: 0.32262098019964064, y: -0.7948390353620646}
      yaw: 270
    neighbors: ["17번", "10번"]


  - name: "17번"
    pose:
      position: {x: 0.34533496030561694, y: -0.2971682700366798}
      yaw: 180
    neighbors: ["16번", "18번"]


  - name: "18번"
    pose:
      position: {x: 0.34533496030561694, y: 0.002948884843199095}
      yaw: 90
    neighbors: ["17번", "19번", "11번"]


  - name: "19번"
    pose:
      position: {x: 0.34533496030561694, y: 0.5859880393965387}
      yaw: 270
    neighbors: ["20번", "18번"]


  - name: "20번"
    pose:
      position: {x: 0.34533496030561694, y: 1.040160507214238}
      yaw: 0
    neighbors: ["21번", "19번", "13번"]


  - name: "21번"
    pose:
      position: {x: 0.34533496030561694, y: 1.3421251900030378}
      yaw: 270
    neighbors: ["22번", "20번"]


  - name: "22번"
    pose:
      position: {x: 0.34533496030561694, y: 1.8305054158827394}
      yaw: 180
    neighbors: ["15번", "21번"]

